name: app_ascs
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^8.1.3
  google_sign_in: ^6.1.5 # Para autenticación con Google
  http: ^0.13.3
  http_parser: ^4.0.2
  path_provider: ^2.1.1 # Para manejo de rutas de archivos
  googleapis: ^11.4.0
  googleapis_auth: ^1.4.1
  amplify_flutter: ^2.6.1 # Para Amplify
  amplify_storage_s3: ^2.6.1 # Para almacenamiento en S3
  amplify_core: ^2.6.1 # Para Amplify Core
  amplify_auth_cognito: ^2.6.1 # Para autenticación con Cognito
  amplify_api: ^2.6.1 # Para API de Amplify

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # Activa la sección de assets si tienes imágenes o recursos específicos
  assets:
    - assets/imagenes/foco_auscultacion.jpg

  #
  # Activa la sección de fonts si tienes fuentes personalizadas
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
